### ISSUE TITLE
readme添加插件列表说明

### ISSUE THREAD

**Issue by lizhuangs** [ukui/peony-extensions#13]
我在peony上面提问说是这里有压缩解压插件，但是readme中没有说有什么插件可用的？
能否在readme上添加插件列表的说明呢？
我看源码似乎有压缩、在终端打开和share（我猜是共享？）几个功能。

**Comment by Yue-Lan** [comment]
可以先参考debian/control下的包描述，README之后补全一下

**Comment by Yue-Lan** [comment]
稍微更新了一下README
