### ISSUE TITLE
插件不可用

### ISSUE THREAD

**Issue by lizhuangs** [ukui/peony-extensions#15]
你好，我编译插件后，有一个testdir，不知道是不是这个。
将其下的3个.so文件复制到了/usr/lib/peony-qt-extensions/
然后打开peony后
1、右键选中文件压缩没反应
2、右键打开终端可以
3、左上角的打开终端没反应
4、还有一个share的插件，不知道怎么用，没看到操作的地方

**Comment by Yue-Lan** [comment]
一些插件可能调用了二进制文件，所以这些插件也是有相关依赖的，比如压缩插件要依赖engrampa，具体可以参考debian/control文件

share在右键菜单的属性窗口中

**Comment by lizhuangs** [comment]
感谢回复，压缩可以用了。但是
1、左上角的打开终端没反应
2、share在右键菜单的属性窗口中我还是没看到这个，无论是否选中文件右键没看到相关的信息。properties中也只有自带的2个选项卡。

**Comment by Yue-Lan** [comment]
> 感谢回复，压缩可以用了。但是
1、左上角的打开终端没反应

应该是没有找到终端应用，有点问题

> 2、share在右键菜单的属性窗口中我还是没看到这个，无论是否选中文件右键没看到相关的信息。properties中也只有自带的2个选项卡。

那可能是libpeony-qt-share.so没有拷贝到目录下，插件的安装主要借助了debhelper，写的比较乱

**Comment by Yue-Lan** [comment]
已经重构qmake工程文件，不用再手动拷贝，直接build然后make install就可以安装

不过一些插件的二进制兼容的问题依然存在
