### ISSUE TITLE
qmake binary name should be qmake-qt5 on fedora

### ISSUE THREAD

**Issue by jenningsloy318** [ukui/peony-extensions#23]
as title indecate, we make modify Cmakefile.list , rename `qmake` to `qmake-qt5`

**Comment by Yue-Lan** [comment]
There is no such command in my system... Do you have any way to resolove with this problem?

**Comment by jenningsloy318** [comment]
on fedora, qmake is qmake-qt5, so if possible we can let compiler to detect it
