### ISSUE TITLE
打开终端大概率失效

### ISSUE THREAD

**Issue by moshengrenzenme** [ukui/peony-extensions#3]

**Comment by MeganHemh** [comment]
Is this happened in version 2004? Please provide the working path when is fails, it will be helpful to solve this issue, thanks!

**Comment by moshengrenzenme** [comment]
> Is this happened in version 2004? Please provide the working path when is fails, it will be helpful to solve this issue, thanks!

抱歉，英语不好，只能回复汉语了，我这是在2004出现的，我把大部分项目放到了home的project里，这个时候尝试右键在此打开终端的时候会无法打开，但是桌面好像是可以的，因为路径是全英文，所以不存在中文路径的问题，还有就是如果先打开一次终端再使用这个选项就会有比较大的几率可以成功打开，是不是百分百能打开倒是没有计算过 @MeganHemh

**Comment by xiaodongliu-nudt** [comment]
个人主目录下创建project文件夹确实会复现该问题 @MeganHemh

**Comment by MeganHemh** [comment]
当打开终端失败的时候，尝试另外一种方式再去打开一次，本周集成新版本后可验证是否解决问题了。

**Comment by xiaodongliu-nudt** [comment]
Version：20200327 fixed
